language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t suryasindwani/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true suryasindwani/docker-react npm run test -- --coverage